// Code generated by protoc-gen-go.
// source: msg.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	msg.proto

It has these top-level messages:
	Message
	MessageWithOffset
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Message) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type MessageWithOffset struct {
	Offset  int64    `protobuf:"varint,1,opt,name=offset" json:"offset,omitempty"`
	Message *Message `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *MessageWithOffset) Reset()                    { *m = MessageWithOffset{} }
func (m *MessageWithOffset) String() string            { return proto.CompactTextString(m) }
func (*MessageWithOffset) ProtoMessage()               {}
func (*MessageWithOffset) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MessageWithOffset) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *MessageWithOffset) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "pb.Message")
	proto.RegisterType((*MessageWithOffset)(nil), "pb.MessageWithOffset")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x2d, 0x4e, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x52, 0xe5, 0x62, 0xf7, 0x4d, 0x2d,
	0x2e, 0x4e, 0x4c, 0x4f, 0x15, 0xe2, 0xe6, 0x62, 0xce, 0x4e, 0xad, 0x94, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x11, 0xe2, 0xe5, 0x62, 0x2d, 0x4b, 0xcc, 0x29, 0x4d, 0x95, 0x60, 0x02, 0x71, 0x95, 0x1c,
	0xb9, 0x04, 0xa1, 0xca, 0xc2, 0x33, 0x4b, 0x32, 0xfc, 0xd3, 0xd2, 0x8a, 0x53, 0x4b, 0x84, 0xf8,
	0xb8, 0xd8, 0xf2, 0xc1, 0x2c, 0xb0, 0x1e, 0x66, 0x21, 0x19, 0x2e, 0xf6, 0x5c, 0x88, 0x22, 0xb0,
	0x2e, 0x6e, 0x23, 0x6e, 0xbd, 0x82, 0x24, 0x3d, 0xa8, 0xbe, 0x24, 0x36, 0xb0, 0xa5, 0xc6, 0x80,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x2e, 0x8a, 0xff, 0x81, 0x00, 0x00, 0x00,
}
