// Code generated by protoc-gen-go.
// source: public.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	public.proto

It has these top-level messages:
	Messages
	Message
	MessageWithOffset
	ClientID
	SubscribeRequest
	PublishRequest
	PublishResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Messages struct {
	Messages []*MessageWithOffset `protobuf:"bytes,1,rep,name=messages" json:"messages,omitempty"`
}

func (m *Messages) Reset()                    { *m = Messages{} }
func (m *Messages) String() string            { return proto.CompactTextString(m) }
func (*Messages) ProtoMessage()               {}
func (*Messages) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Messages) GetMessages() []*MessageWithOffset {
	if m != nil {
		return m.Messages
	}
	return nil
}

type Message struct {
	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Message) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Message) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type MessageWithOffset struct {
	Offset  int64    `protobuf:"varint,1,opt,name=offset" json:"offset,omitempty"`
	Message *Message `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *MessageWithOffset) Reset()                    { *m = MessageWithOffset{} }
func (m *MessageWithOffset) String() string            { return proto.CompactTextString(m) }
func (*MessageWithOffset) ProtoMessage()               {}
func (*MessageWithOffset) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MessageWithOffset) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *MessageWithOffset) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type ClientID struct {
	ConsumerGroup string `protobuf:"bytes,1,opt,name=consumerGroup" json:"consumerGroup,omitempty"`
	ConsumerID    string `protobuf:"bytes,2,opt,name=consumerID" json:"consumerID,omitempty"`
}

func (m *ClientID) Reset()                    { *m = ClientID{} }
func (m *ClientID) String() string            { return proto.CompactTextString(m) }
func (*ClientID) ProtoMessage()               {}
func (*ClientID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ClientID) GetConsumerGroup() string {
	if m != nil {
		return m.ConsumerGroup
	}
	return ""
}

func (m *ClientID) GetConsumerID() string {
	if m != nil {
		return m.ConsumerID
	}
	return ""
}

type SubscribeRequest struct {
	ClientID  *ClientID `protobuf:"bytes,1,opt,name=clientID" json:"clientID,omitempty"`
	Topic     string    `protobuf:"bytes,2,opt,name=topic" json:"topic,omitempty"`
	Partition int32     `protobuf:"varint,3,opt,name=partition" json:"partition,omitempty"`
}

func (m *SubscribeRequest) Reset()                    { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string            { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()               {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SubscribeRequest) GetClientID() *ClientID {
	if m != nil {
		return m.ClientID
	}
	return nil
}

func (m *SubscribeRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *SubscribeRequest) GetPartition() int32 {
	if m != nil {
		return m.Partition
	}
	return 0
}

type PublishRequest struct {
	Topic     string     `protobuf:"bytes,1,opt,name=topic" json:"topic,omitempty"`
	Partition int32      `protobuf:"varint,2,opt,name=partition" json:"partition,omitempty"`
	Messages  []*Message `protobuf:"bytes,3,rep,name=messages" json:"messages,omitempty"`
}

func (m *PublishRequest) Reset()                    { *m = PublishRequest{} }
func (m *PublishRequest) String() string            { return proto.CompactTextString(m) }
func (*PublishRequest) ProtoMessage()               {}
func (*PublishRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PublishRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *PublishRequest) GetPartition() int32 {
	if m != nil {
		return m.Partition
	}
	return 0
}

func (m *PublishRequest) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type PublishResponse struct {
	Offsets []int64 `protobuf:"varint,1,rep,packed,name=offsets" json:"offsets,omitempty"`
}

func (m *PublishResponse) Reset()                    { *m = PublishResponse{} }
func (m *PublishResponse) String() string            { return proto.CompactTextString(m) }
func (*PublishResponse) ProtoMessage()               {}
func (*PublishResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PublishResponse) GetOffsets() []int64 {
	if m != nil {
		return m.Offsets
	}
	return nil
}

func init() {
	proto.RegisterType((*Messages)(nil), "pb.Messages")
	proto.RegisterType((*Message)(nil), "pb.Message")
	proto.RegisterType((*MessageWithOffset)(nil), "pb.MessageWithOffset")
	proto.RegisterType((*ClientID)(nil), "pb.ClientID")
	proto.RegisterType((*SubscribeRequest)(nil), "pb.SubscribeRequest")
	proto.RegisterType((*PublishRequest)(nil), "pb.PublishRequest")
	proto.RegisterType((*PublishResponse)(nil), "pb.PublishResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UltrabusNode service

type UltrabusNodeClient interface {
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (UltrabusNode_SubscribeClient, error)
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
}

type ultrabusNodeClient struct {
	cc *grpc.ClientConn
}

func NewUltrabusNodeClient(cc *grpc.ClientConn) UltrabusNodeClient {
	return &ultrabusNodeClient{cc}
}

func (c *ultrabusNodeClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (UltrabusNode_SubscribeClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_UltrabusNode_serviceDesc.Streams[0], c.cc, "/pb.UltrabusNode/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &ultrabusNodeSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UltrabusNode_SubscribeClient interface {
	Recv() (*Messages, error)
	grpc.ClientStream
}

type ultrabusNodeSubscribeClient struct {
	grpc.ClientStream
}

func (x *ultrabusNodeSubscribeClient) Recv() (*Messages, error) {
	m := new(Messages)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ultrabusNodeClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	out := new(PublishResponse)
	err := grpc.Invoke(ctx, "/pb.UltrabusNode/Publish", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UltrabusNode service

type UltrabusNodeServer interface {
	Subscribe(*SubscribeRequest, UltrabusNode_SubscribeServer) error
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
}

func RegisterUltrabusNodeServer(s *grpc.Server, srv UltrabusNodeServer) {
	s.RegisterService(&_UltrabusNode_serviceDesc, srv)
}

func _UltrabusNode_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UltrabusNodeServer).Subscribe(m, &ultrabusNodeSubscribeServer{stream})
}

type UltrabusNode_SubscribeServer interface {
	Send(*Messages) error
	grpc.ServerStream
}

type ultrabusNodeSubscribeServer struct {
	grpc.ServerStream
}

func (x *ultrabusNodeSubscribeServer) Send(m *Messages) error {
	return x.ServerStream.SendMsg(m)
}

func _UltrabusNode_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UltrabusNodeServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UltrabusNode/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UltrabusNodeServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UltrabusNode_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.UltrabusNode",
	HandlerType: (*UltrabusNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _UltrabusNode_Publish_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _UltrabusNode_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "public.proto",
}

func init() { proto.RegisterFile("public.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 342 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xdf, 0x4e, 0xb3, 0x40,
	0x10, 0xc5, 0x4b, 0x09, 0x05, 0x06, 0xda, 0x7e, 0x9d, 0xcf, 0x26, 0xa4, 0x51, 0xd3, 0x6c, 0x62,
	0xec, 0x55, 0x63, 0xa8, 0x3e, 0x80, 0xb1, 0x89, 0xe9, 0x85, 0xff, 0x35, 0x5e, 0x03, 0x6e, 0x2d,
	0x91, 0xb2, 0x2b, 0xbb, 0x6b, 0xd2, 0xb7, 0x37, 0x2c, 0x94, 0xb4, 0xf6, 0x6e, 0x98, 0xc9, 0xf9,
	0x1d, 0xce, 0x01, 0xf0, 0xb9, 0x8a, 0xb3, 0x34, 0x99, 0xf2, 0x82, 0x49, 0x86, 0x6d, 0x1e, 0x93,
	0x19, 0x38, 0x77, 0x54, 0x88, 0xe8, 0x93, 0x0a, 0x3c, 0x07, 0x67, 0x5d, 0xcf, 0x81, 0x31, 0x36,
	0x27, 0x5e, 0x38, 0x9c, 0xf2, 0x78, 0x5a, 0xdf, 0xdf, 0x53, 0xb9, 0x7a, 0x58, 0x2e, 0x05, 0x95,
	0xe4, 0x0c, 0xec, 0x7a, 0x89, 0x1e, 0x98, 0x5f, 0x74, 0x13, 0x18, 0x63, 0x63, 0xe2, 0x63, 0x17,
	0xac, 0x9f, 0x28, 0x53, 0x34, 0x68, 0x97, 0x8f, 0xe4, 0x1a, 0x06, 0x07, 0x5a, 0xec, 0x41, 0x87,
	0xe9, 0x49, 0x6b, 0x4c, 0x3c, 0x06, 0xbb, 0x36, 0xd5, 0x2a, 0x2f, 0xf4, 0x76, 0x3c, 0xc9, 0x15,
	0x38, 0x37, 0x59, 0x4a, 0x73, 0xb9, 0x98, 0xe3, 0x10, 0xba, 0x09, 0xcb, 0x85, 0x5a, 0xd3, 0xe2,
	0xb6, 0x60, 0x8a, 0x6b, 0x80, 0x8b, 0x08, 0xb0, 0x5d, 0x2f, 0xe6, 0x9a, 0xe1, 0x92, 0x57, 0xf8,
	0xf7, 0xa2, 0x62, 0x91, 0x14, 0x69, 0x4c, 0x9f, 0xe9, 0xb7, 0xa2, 0x42, 0xe2, 0x29, 0x38, 0x49,
	0x8d, 0xd2, 0x4a, 0x2f, 0xf4, 0x4b, 0xa7, 0x06, 0xdf, 0x05, 0x4b, 0x32, 0x9e, 0x26, 0x15, 0x02,
	0x07, 0xe0, 0xf2, 0xa8, 0x90, 0xa9, 0x4c, 0x59, 0x1e, 0x98, 0x63, 0x63, 0x62, 0x91, 0x27, 0xe8,
	0x3d, 0x96, 0xfd, 0x89, 0xd5, 0x96, 0xd9, 0x68, 0x8c, 0x43, 0x4d, 0x89, 0xb1, 0xf0, 0x64, 0xa7,
	0x53, 0x53, 0x77, 0xba, 0x97, 0x8f, 0x40, 0xbf, 0x41, 0x0a, 0xce, 0x72, 0x41, 0xb1, 0x0f, 0x76,
	0x55, 0x50, 0xf5, 0x11, 0xcc, 0x70, 0x03, 0xfe, 0x5b, 0x26, 0x8b, 0x28, 0x56, 0xe2, 0x9e, 0x7d,
	0x50, 0x9c, 0x81, 0xdb, 0x84, 0xc3, 0xa3, 0x92, 0xf6, 0x37, 0xeb, 0xc8, 0xdf, 0xf1, 0x10, 0xa4,
	0x75, 0x61, 0xe0, 0x25, 0xd8, 0xb5, 0x11, 0x62, 0x79, 0xdc, 0x0f, 0x32, 0xfa, 0xbf, 0xb7, 0xab,
	0xde, 0x84, 0xb4, 0xe2, 0x8e, 0xfe, 0x51, 0x66, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xda, 0x0e,
	0x0b, 0xe2, 0x38, 0x02, 0x00, 0x00,
}
